[features]
seeds = false
skip-lint = false
[programs.localnet]
calculator = "HsUabeV6q3463kJdRcrdULZv2QeaghfkTrttGjdt7gVY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/yash/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
